package GreenDao3;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.liuwen.two.Bean.Catalog;

import GreenDao3.CatalogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig catalogDaoConfig;

    private final CatalogDao catalogDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        catalogDaoConfig = daoConfigMap.get(CatalogDao.class).clone();
        catalogDaoConfig.initIdentityScope(type);

        catalogDao = new CatalogDao(catalogDaoConfig, this);

        registerDao(Catalog.class, catalogDao);
    }
    
    public void clear() {
        catalogDaoConfig.clearIdentityScope();
    }

    public CatalogDao getCatalogDao() {
        return catalogDao;
    }

}
