package GreenDao3;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.liuwen.two.Bean.Catalog;
import com.example.liuwen.two.Bean.Book;

import GreenDao3.CatalogDao;
import GreenDao3.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig catalogDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final CatalogDao catalogDao;
    private final BookDao bookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        catalogDaoConfig = daoConfigMap.get(CatalogDao.class).clone();
        catalogDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        catalogDao = new CatalogDao(catalogDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(Catalog.class, catalogDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        catalogDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
    }

    public CatalogDao getCatalogDao() {
        return catalogDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
